language: go


go:
- 1.11
- tip


matrix:
  allow_failures:
  - go: tip


before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover


#install:
#- go get -d -v -t ./...


script:
- GO111MODULE=on go install ./cmd/...
- GO111MODULE=on go test -v ./
- GO111MODULE=on go test -covermode=count -coverprofile=profile.out .
- goveralls -covermode=count -service=travis-ci -v -coverprofile=profile.out
